### ISSUE TITLE
Errors when installing project according to readme instructions

### ISSUE THREAD

**Issue by grahamalama** [plotly/dash-core-components#459]
Installing project on MacOS 10.14.2 x64
Using NVM and node v11.7.0

 - Cloned repo

 - ran npm i

 - Encountered warnings after node install:
```
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@11.7.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
```

 - Encountered error at end:

```
30164 info lifecycle dash-core-components@0.43.1~prepare: dash-core-components@0.43.1
30165 verbose lifecycle dash-core-components@0.43.1~prepare: unsafe-perm in lifecycle true
30166 verbose lifecycle dash-core-components@0.43.1~prepare: PATH: /Users/grahamalama/.nvm/versions/node/v11.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/grahamalama/dev/dash_architecture_exploration/dash-core-components/node_modules/.bin:/Users/grahamalama/Library/Android/sdk/platform-tools:/Users/grahamalama/.pyenv/shims:/Users/grahamalama/.rvm/gems/ruby-2.4.1/bin:/Users/grahamalama/.rvm/gems/ruby-2.4.1@global/bin:/Users/grahamalama/.rvm/rubies/ruby-2.4.1/bin:/Users/grahamalama/.nvm/versions/node/v11.7.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/grahamalama/.rvm/bin
30167 verbose lifecycle dash-core-components@0.43.1~prepare: CWD: /Users/grahamalama/dev/dash_architecture_exploration/dash-core-components
30168 silly lifecycle dash-core-components@0.43.1~prepare: Args: [ '-c', 'npm run build:all' ]
30169 silly lifecycle dash-core-components@0.43.1~prepare: Returned: code: 1  signal: null
30170 info lifecycle dash-core-components@0.43.1~prepare: Failed to exec prepare script
30171 verbose stack Error: dash-core-components@0.43.1 prepare: `npm run build:all`
30171 verbose stack Exit status 1
30171 verbose stack     at EventEmitter.<anonymous> (/Users/grahamalama/.nvm/versions/node/v11.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
30171 verbose stack     at EventEmitter.emit (events.js:188:13)
30171 verbose stack     at ChildProcess.<anonymous> (/Users/grahamalama/.nvm/versions/node/v11.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
30171 verbose stack     at ChildProcess.emit (events.js:188:13)
30171 verbose stack     at maybeClose (internal/child_process.js:978:16)
30171 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
30172 verbose pkgid dash-core-components@0.43.1
30173 verbose cwd /Users/grahamalama/dev/dash_architecture_exploration/dash-core-components
30174 verbose Darwin 18.2.0
30175 verbose argv "/Users/grahamalama/.nvm/versions/node/v11.7.0/bin/node" "/Users/grahamalama/.nvm/versions/node/v11.7.0/bin/npm" "i"
30176 verbose node v11.7.0
30177 verbose npm  v6.5.0
30178 error code ELIFECYCLE
30179 error errno 1
30180 error dash-core-components@0.43.1 prepare: `npm run build:all`
30180 error Exit status 1
30181 error Failed at the dash-core-components@0.43.1 prepare script.
30181 error This is probably not a problem with npm. There is likely additional logging output above.
30182 verbose exit [ 1, true ]
```

 - Tried `npm run:build` after, another error:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/grahamalama/.nvm/versions/node/v11.7.0/bin/node',
1 verbose cli   '/Users/grahamalama/.nvm/versions/node/v11.7.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:all' ]
2 info using npm@6.5.0
3 info using node@v11.7.0
4 verbose run-script [ 'prebuild:all', 'build:all', 'postbuild:all' ]
5 info lifecycle dash-core-components@0.43.1~prebuild:all: dash-core-components@0.43.1
6 info lifecycle dash-core-components@0.43.1~build:all: dash-core-components@0.43.1
7 verbose lifecycle dash-core-components@0.43.1~build:all: unsafe-perm in lifecycle true
8 verbose lifecycle dash-core-components@0.43.1~build:all: PATH: /Users/grahamalama/.nvm/versions/node/v11.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/grahamalama/dev/dash_architecture_exploration/dash-core-components/node_modules/.bin:/Users/grahamalama/Library/Android/sdk/platform-tools:/Users/grahamalama/.pyenv/shims:/Users/grahamalama/.rvm/gems/ruby-2.4.1/bin:/Users/grahamalama/.rvm/gems/ruby-2.4.1@global/bin:/Users/grahamalama/.rvm/rubies/ruby-2.4.1/bin:/Users/grahamalama/.nvm/versions/node/v11.7.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/grahamalama/.rvm/bin
9 verbose lifecycle dash-core-components@0.43.1~build:all: CWD: /Users/grahamalama/dev/dash_architecture_exploration/dash-core-components
10 silly lifecycle dash-core-components@0.43.1~build:all: Args: [ '-c',
10 silly lifecycle   'npm run build:js && npm run build:js-dev && npm run build:py' ]
11 silly lifecycle dash-core-components@0.43.1~build:all: Returned: code: 1  signal: null
12 info lifecycle dash-core-components@0.43.1~build:all: Failed to exec build:all script
13 verbose stack Error: dash-core-components@0.43.1 build:all: `npm run build:js && npm run build:js-dev && npm run build:py`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/grahamalama/.nvm/versions/node/v11.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:188:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/grahamalama/.nvm/versions/node/v11.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:188:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid dash-core-components@0.43.1
15 verbose cwd /Users/grahamalama/dev/dash_architecture_exploration/dash-core-components
16 verbose Darwin 18.2.0
17 verbose argv "/Users/grahamalama/.nvm/versions/node/v11.7.0/bin/node" "/Users/grahamalama/.nvm/versions/node/v11.7.0/bin/npm" "run" "build:all"
18 verbose node v11.7.0
19 verbose npm  v6.5.0
20 error code ELIFECYCLE
21 error errno 1
22 error dash-core-components@0.43.1 build:all: `npm run build:js && npm run build:js-dev && npm run build:py`
22 error Exit status 1
23 error Failed at the dash-core-components@0.43.1 build:all script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

 - I then create a new virtualenv 
  `virtualenv venv -p python3`
  `source venv/bin/activate`

 - And then try running `npm i` again. This time, there are no error messages, but I get the following output for each component:

```
Description for [component].id is missing!

Generated [component].py
```

**Comment by thinkjrs** [comment]
Having similar issues as @grahamalama in getting the dev environment setup. I'm able to build the js components but the runner is unable to find the script `dash-generate-components` in line 29 of the `package.json` file.  

@rpkyle Looks like you've been working on this area of the codebase lately--any idea what's going on or how we might be able to implement a workaround in the short term? Thanks!

**Comment by dhuang612** [comment]
Hi, 

I'm having similar issues trying to get this project up and running from the readme files.

I can get up to running npm run build it then outputs the following and freezes:
```
webpack --mode production
```
I was able to setup the virtual env without issue in python.

Thanks
