### ISSUE TITLE
Invalid argument `value` passed into dcc.Input 

### ISSUE THREAD

**Issue by dmitra79** [plotly/dash-core-components#797]
Hello,

I get an error when trying to set either 'value' or 'placeholder' on dcc.Input via callback. 
```
dcc.Input(id='annotation', placeholder='Enter input here...',  value=None, type='text')
```
Error:
```
Invalid argument `value` passed into Input with ID "annotation".
Value provided: 
[
  "ok!!!"
]
```
The full JS error is:
```
Error: Invalid argument `value` passed into Input with ID "annotation".

Value provided: 

[

  "ok!!!"

]

    at propTypeErrorHandler (http://129.73.9.203:8050/_dash-component-suites/dash_renderer/dash_renderer.v1_2_3m1580483115.dev.js:33412:9)

    at CheckedComponent (http://129.73.9.203:8050/_dash-component-suites/dash_renderer/dash_renderer.v1_2_3m1580483115.dev.js:29906:77)

    at renderWithHooks (http://129.73.9.203:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_2_3m1580483115.8.6.js:13073:18)

    at updateFunctionComponent (http://129.73.9.203:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_2_3m1580483115.8.6.js:14762:20)

    at beginWork (http://129.73.9.203:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_2_3m1580483115.8.6.js:15772:16)

    at performUnitOfWork (http://129.73.9.203:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_2_3m1580483115.8.6.js:19447:12)

    at workLoop (http://129.73.9.203:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_2_3m1580483115.8.6.js:19487:24)

    at renderRoot (http://129.73.9.203:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_2_3m1580483115.8.6.js:19570:7)

    at performWorkOnRoot (http://129.73.9.203:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_2_3m1580483115.8.6.js:20477:7)

    at performWork (http://129.73.9.203:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_2_3m1580483115.8.6.js:20389:7)
```

I was using 'value' of the Input in a callback State already, and after finding
https://github.com/plotly/dash-core-components/issues/430
I tried the dummy hidden div workaround described there to have it in a callbak Input, but no luck.
Any suggestions would be appreciated!

My environment: Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-45-generic x86_64)
python                    3.7.5                h0371630_0
dash                      1.8.0                      py_0    conda-forge
dash-core-components      1.7.0                      py_0    conda-forge
dash-html-components      1.0.2                      py_0    conda-forge
dash-renderer             1.2.3                      py_0    conda-forge
dash-table                4.6.0                      py_0    conda-forge

**Comment by alexcjohnson** [comment]
It looks like your callback is returning a list containing the desired string, when it should return only the string.

**Comment by dmitra79** [comment]
Thanks, that was it!

**Comment by jbebic** [comment]
Ran into the same problem when returning numpy values. 
Use `yval.item()` to convert a numpy scalar to a native Python type.
If you don't like too many decimals, use: `yval.round(3).item()`
